site_name: "Family Camping Protocol"
theme:
  name: "material"
  language: en
  locale: ja

nav:
  - English:
      - Home: en/index.md
      - Packing List: en/packing-list.md
  - 日本語:
      - ホーム: ja/index.md
      - 持ち物リスト: ja/packing-list.md